{
    "name": "Open Paye",
    "version": "0.9",
    "depends": ["account","hr","jasper_server"],
    "author": "Sudokeys",
    "category": "",
    "description": """
    Moteur de paie généric 
    """,
    'data': [
        'security/ir.model.access.csv',
        'view_params_dict.xml',
        'view_param_model.xml',
        'view_paramsval.xml',
        'view_payslip_line.xml',
        'view_res_partner.xml',
        'view_payslip.xml',
        'view_org_cotis.xml',
        'view_dadsu.xml',
        'view_legalframe.xml',
        'view_company.xml',
        'view_activity.xml',
        'view_employee.xml',
        'view_contractframe.xml',
        'view_payrun.xml',
        'view_calendar.xml',
        'view_cumann.xml',
        'hr_gp_view.xml',
        'wizard/etat_paiement_view.xml',
        'wizard/create_model_view.xml',
        'wizard/seqparams_view.xml',
        'wizard/inversepay_view.xml',
        'wizard/getantecdesc_view.xml',
        'wizard/support.xml',
        'wizard/resume_cotis_view.xml',
        'wizard/ducs_view.xml',
        'wizard/etat_comptable_view.xml',
        'wizard/recap_paye_view.xml',
        'wizard/allegements_view.xml',
        'wizard/livre_paie_view.xml',
        'wizard/attestation_pole_emploi_view.xml',
        'wizard/stc_view.xml',
        'wizard/certificat_travail_view.xml',
        'wizard/payslip_wizard_view.xml',
        'wizard/accline_validation_view.xml',
        'payslip_workflow.xml',
        'report/report.xml',
    ],
    'demo': [],
    'images': [],
    'installable': True,
    'active': False,
}
